version: '3.8'

services:
  postgres:
    image: postgres:14.0
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: service_mesh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftpFiles:/home/foo/sftpFiles
    ports:
      - "2222:22"
    environment:
      SFTP_USERS: "foo:pass:1001"
 
      
  
  zookeeper:
    image: docker.io/bitnami/zookeeper:3.9
    ports:
      - "2181:2181"
    volumes:
      - "zookeeper_data:/bitnami"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
    image: docker.io/bitnami/kafka:3.4
    ports:
      - "9092:9092"
    volumes:
      - "kafka_data:/bitnami"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
    depends_on:
      - zookeeper

 
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: amd
      MONGO_INITDB_ROOT_PASSWORD: ak
      MONGO_INITDB_DATABASE: EDR


volumes:
  postgres_data:
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local

