version: '3.8'

services:
  postgres:
    image: postgres:14.0
    container_name: my_postgres_container
    environment:
      POSTGRES_DB: serviceMesh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ak
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
   
  sftp:
    image: atmoz/sftp
    volumes:
      - ./sftpFiles:/sftpFiles
    ports:
      - "2222:22"
    environment:
      SFTP_USERS: "foo:pass:1001"
volumes:
  postgres_data:
